/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmDialogLogin.java
 *
 * Created on 23-jun-2012, 0:14:59
 */

package EULEN.COMPUTOS.VISTAS;

import EULEN.COMPUTOS.DATA.DB_COMPUTO;
//import EULEN.COMPUTOS.FUNCIONES.ClavedelDia;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JDialog;

/**
 *
 * @author jmsanchez
 */
public class Login extends javax.swing.JDialog {
    java.sql.ResultSet rs;
    public DB_COMPUTO BD;
    //public ClavedelDia clave = new ClavedelDia();
    
    /** Creates new form frmDialogLogin */
    public Login(javax.swing.JDialog parent, boolean modal) {
        super(parent,modal);
        setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("ImagenUsuarioReloj.jpg")));
        initComponents(); 
        cargarUsuarios();
        this.jCmbUsuarios.addItem("Administrador");
        this.jCmbUsuarios.setSelectedIndex(-1);
        this.setAlwaysOnTop(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jBtnEntrar = new javax.swing.JButton();
        JBtnSalir = new javax.swing.JButton();
        jLbl_Usuario = new javax.swing.JLabel();
        jLbl_Password = new javax.swing.JLabel();
        jTxtPassword = new javax.swing.JPasswordField();
        jLbl_Login_LogoPastillaEulen = new javax.swing.JLabel();
        jCmbUsuarios = new javax.swing.JComboBox();
        jLbl_Titulo_AccesoRestringido = new javax.swing.JLabel();

        jOptionPane1.setName("jOptionPane1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(EULEN.COMPUTOS.VISTAS.App.class).getContext().getResourceMap(Login.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        jBtnEntrar.setText(resourceMap.getString("jBtnEntrar.text")); // NOI18N
        jBtnEntrar.setName("jBtnEntrar"); // NOI18N
        jBtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEntrarActionPerformed(evt);
            }
        });

        JBtnSalir.setText(resourceMap.getString("JBtnSalir.text")); // NOI18N
        JBtnSalir.setName("JBtnSalir"); // NOI18N
        JBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnSalirActionPerformed(evt);
            }
        });

        jLbl_Usuario.setText(resourceMap.getString("jLbl_Usuario.text")); // NOI18N
        jLbl_Usuario.setName("jLbl_Usuario"); // NOI18N

        jLbl_Password.setText(resourceMap.getString("jLbl_Password.text")); // NOI18N
        jLbl_Password.setName("jLbl_Password"); // NOI18N

        jTxtPassword.setText(resourceMap.getString("jTxtPassword.text")); // NOI18N
        jTxtPassword.setName("jTxtPassword"); // NOI18N
        jTxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPasswordActionPerformed(evt);
            }
        });
        jTxtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtPasswordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtPasswordKeyTyped(evt);
            }
        });

        jLbl_Login_LogoPastillaEulen.setIcon(resourceMap.getIcon("jLbl_Login_LogoPastillaEulen.icon")); // NOI18N
        jLbl_Login_LogoPastillaEulen.setText(resourceMap.getString("jLbl_Login_LogoPastillaEulen.text")); // NOI18N
        jLbl_Login_LogoPastillaEulen.setName("jLbl_Login_LogoPastillaEulen"); // NOI18N

        jCmbUsuarios.setName("jCmbUsuarios"); // NOI18N
        jCmbUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCmbUsuariosKeyPressed(evt);
            }
        });

        jLbl_Titulo_AccesoRestringido.setFont(resourceMap.getFont("jLbl_Titulo_AccesoRestringido.font")); // NOI18N
        jLbl_Titulo_AccesoRestringido.setText(resourceMap.getString("jLbl_Titulo_AccesoRestringido.text")); // NOI18N
        jLbl_Titulo_AccesoRestringido.setName("jLbl_Titulo_AccesoRestringido"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLbl_Titulo_AccesoRestringido))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbl_Usuario)
                            .addComponent(jLbl_Password))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jLbl_Login_LogoPastillaEulen, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(JBtnSalir)
                        .addGap(323, 323, 323)
                        .addComponent(jBtnEntrar)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLbl_Titulo_AccesoRestringido)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLbl_Usuario)
                        .addGap(17, 17, 17)
                        .addComponent(jLbl_Password))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jCmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jTxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLbl_Login_LogoPastillaEulen, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBtnSalir)
                    .addComponent(jBtnEntrar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEntrarActionPerformed
        String usuario = this.jCmbUsuarios.getSelectedItem().toString();
        String Password = new String(jTxtPassword.getPassword());
        Calendar wAhora = Calendar.getInstance();
        Date ahora; 
        Date wFechaUltCambio;
        int clavedelDia;
        
        //clavedelDia =  clave.getClavedelDia();
        if (usuario.equals("Administrador")){
            if (Password.toUpperCase().trim().equals("EULEN.COM")){
               EULEN.COMPUTOS.VISTAS.Main.wGrupoUsuarios = 0;
               EULEN.COMPUTOS.VISTAS.Main.wNombreUsuario = "Administrador del Programa";
               EULEN.COMPUTOS.VISTAS.Main.LG_Activo = 1;
               EULEN.COMPUTOS.VISTAS.Main.LG_Administrador = 1;
               EULEN.COMPUTOS.VISTAS.Main.seguir = true;
               EULEN.COMPUTOS.VISTAS.Main.wUsuario= usuario.toUpperCase();
               EULEN.COMPUTOS.VISTAS.Main.LG_CambioPaswword = false;
               javax.swing.JOptionPane.showMessageDialog(this,  "BIENVENIDO, " + EULEN.COMPUTOS.VISTAS.Main.wNombreUsuario.toUpperCase() +"." ," IDENTIFICACIÓN SATISFACTORIA", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
               EULEN.COMPUTOS.VISTAS.Main.seguir = false;
               javax.swing.JOptionPane.showMessageDialog(this,  "La contraseña introducida no es correcta para el usuario Administrador.","INFORMACIÓN DE ERROR", javax.swing.JOptionPane.INFORMATION_MESSAGE);    
            }
        } else {
            try{
                BD = new DB_COMPUTO();
                String strsql ="SELECT * FROM COMPUTOS.GESTORES WHERE TX_NOMBRE = '" + usuario + "' AND TX_PASSWORD = '" + Password + "'" ;
                rs=BD.Consulta(strsql);
                rs.last();
                int i = rs.getRow();
                if (i <1){ // && !Password.equals(String.valueOf(clavedelDia).trim())){
                   EULEN.COMPUTOS.VISTAS.Main.seguir = false;
                }
                else{
                   EULEN.COMPUTOS.VISTAS.Main.wGrupoUsuarios = rs.getInt("NM_GESTOR");
                   EULEN.COMPUTOS.VISTAS.Main.wNombreUsuario = rs.getString("TX_NOMBRE");
                   EULEN.COMPUTOS.VISTAS.Main.LG_Activo = 1;
                   EULEN.COMPUTOS.VISTAS.Main.LG_Administrador = 1;
                   EULEN.COMPUTOS.VISTAS.Main.seguir = true;
                   EULEN.COMPUTOS.VISTAS.Main.wUsuario= usuario.toUpperCase();
                   EULEN.COMPUTOS.VISTAS.Main.LG_CambioPaswword = false;
                }
                javax.swing.JOptionPane.showMessageDialog(this,  "BIENVENIDO, " + EULEN.COMPUTOS.VISTAS.Main.wNombreUsuario.toUpperCase() +"." ," IDENTIFICACIÓN SATISFACTORIA", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                BD.cerrarConexion();
            }
            catch (Exception e) {
                EULEN.COMPUTOS.VISTAS.Main.seguir = false;
                javax.swing.JOptionPane.showMessageDialog(this,  "ERROR: " + e.toString(),"INFORMACIÓN DE ERROR", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
        }
       dispose();
}//GEN-LAST:event_jBtnEntrarActionPerformed

    private void JBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnSalirActionPerformed
        
        EULEN.COMPUTOS.VISTAS.Main.salir=true;
        dispose();
        System.exit(0);
    }//GEN-LAST:event_JBtnSalirActionPerformed

    private void jTxtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPasswordKeyTyped
        
    }//GEN-LAST:event_jTxtPasswordKeyTyped

    private void jTxtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPasswordKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          jBtnEntrarActionPerformed(null);
        }

    }//GEN-LAST:event_jTxtPasswordKeyPressed

    private void jTxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPasswordActionPerformed
        
    }//GEN-LAST:event_jTxtPasswordActionPerformed

    private void jCmbUsuariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCmbUsuariosKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          //this.jTxtPassword.setf;
            this.jCmbUsuarios.transferFocus();
        }

    }//GEN-LAST:event_jCmbUsuariosKeyPressed
private void cargarUsuarios(){
      String strsql ="SELECT TX_NOMBRE FROM COMPUTOS.GESTORES ORDER BY 1;";
       try{
            BD = new DB_COMPUTO();
            rs=BD.Consulta(strsql);
            rs.last();
            int i = rs.getRow();
            rs.beforeFirst();
            if (i >=1){
                this.jCmbUsuarios.removeAllItems();
                while (rs.next()){
                  this.jCmbUsuarios.addItem(rs.getString("TX_NOMBRE"));
                }
            }
            BD.cerrarConexion();
         }
        catch (Exception e) {
           javax.swing.JOptionPane.showMessageDialog(this,  "Conexión ERRONEA a la Base de Datos","Error de Conexión", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
}
            /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login dialog = new Login(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private void cambiarPassword(){
    /*  Password pass = new Password(new javax.swing.JDialog(),true);
      pass.setLocationRelativeTo(null);
      pass.setVisible(true);
     * 
     */
     }
    private boolean isDate(String fechax) {
        try {

            SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-DD");
            Date fecha = formatoFecha.parse(fechax);
        } catch (Exception e) {
            return false;
        }
        return true;
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnSalir;
    private javax.swing.JButton jBtnEntrar;
    private javax.swing.JComboBox jCmbUsuarios;
    private javax.swing.JLabel jLbl_Login_LogoPastillaEulen;
    private javax.swing.JLabel jLbl_Password;
    private javax.swing.JLabel jLbl_Titulo_AccesoRestringido;
    private javax.swing.JLabel jLbl_Usuario;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPasswordField jTxtPassword;
    // End of variables declaration//GEN-END:variables

}
