/*
 * Main.java
 */

package EULEN.COMPUTOS.VISTAS;

import java.awt.Toolkit;
import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * The application's main frame.
 */
public class Main extends FrameView {
    public static boolean seguir;
    public String vecesMas="";
    public static String wUsuario="";
    public static String wNombreUsuario="";
    public static int wGrupoUsuarios = 0;
    public static int LG_Activo =0;
    public static boolean salir;
    public static int LG_Administrador = 0;
    public static boolean LG_CambioPaswword;
       

    public Main(SingleFrameApplication app) {
        super(app);

        initComponents();
        String path = this.getClass().getResource("").getPath();
        this.getFrame().setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("ImagenUsuarioReloj.jpg")));
        //ImagenUsuarioReloj.jpg

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
        entrarUsuarioyContraseña();    
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = App.getApplication().getMainFrame();
            aboutBox = new Acerca(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        App.getApplication().show(aboutBox);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLbl_Titulo = new javax.swing.JLabel();
        jLbl_Logo1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu jMnuHoras = new javax.swing.JMenu();
        jMnuConsulta = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuCambiardeUsuario = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        mainPanel.setName("mainPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(EULEN.COMPUTOS.VISTAS.App.class).getContext().getResourceMap(Main.class);
        jLbl_Titulo.setFont(resourceMap.getFont("jLbl_Titulo.font")); // NOI18N
        jLbl_Titulo.setForeground(resourceMap.getColor("jLbl_Titulo.foreground")); // NOI18N
        jLbl_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_Titulo.setText(resourceMap.getString("jLbl_Titulo.text")); // NOI18N
        jLbl_Titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLbl_Titulo.setName("jLbl_Titulo"); // NOI18N

        jLbl_Logo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_Logo1.setIcon(resourceMap.getIcon("jLbl_Logo1.icon")); // NOI18N
        jLbl_Logo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLbl_Logo1.setName("jLbl_Logo1"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbl_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 997, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLbl_Logo1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addGap(223, 223, 223))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLbl_Titulo)
                .addGap(75, 75, 75)
                .addComponent(jLbl_Logo1)
                .addGap(20, 20, 20))
        );

        menuBar.setName("menuBar"); // NOI18N

        jMnuHoras.setText(resourceMap.getString("jMnuHoras.text")); // NOI18N
        jMnuHoras.setName("jMnuHoras"); // NOI18N
        jMnuHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuHorasActionPerformed(evt);
            }
        });

        jMnuConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsulta.setText(resourceMap.getString("jMnuConsulta.text")); // NOI18N
        jMnuConsulta.setName("jMnuConsulta"); // NOI18N
        jMnuConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultaActionPerformed(evt);
            }
        });
        jMnuHoras.add(jMnuConsulta);

        jSeparator1.setName("jSeparator1"); // NOI18N
        jMnuHoras.add(jSeparator1);

        jMnuCambiardeUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuCambiardeUsuario.setText(resourceMap.getString("jMnuCambiardeUsuario.text")); // NOI18N
        jMnuCambiardeUsuario.setName("jMnuCambiardeUsuario"); // NOI18N
        jMnuCambiardeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuCambiardeUsuarioActionPerformed(evt);
            }
        });
        jMnuHoras.add(jMnuCambiardeUsuario);

        jSeparator2.setName("jSeparator2"); // NOI18N
        jMnuHoras.add(jSeparator2);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(EULEN.COMPUTOS.VISTAS.App.class).getContext().getActionMap(Main.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setText(resourceMap.getString("exitMenuItem.text")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        jMnuHoras.add(exitMenuItem);

        menuBar.add(jMnuHoras);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setText(resourceMap.getString("aboutMenuItem.text")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 997, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 827, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuHorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuHorasActionPerformed

    private void jMnuConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultaActionPerformed
        // TODO add your handling code here:
        Consulta frmConsulta = new Consulta(new javax.swing.JDialog(),true);
        frmConsulta.setLocationRelativeTo(null);
        frmConsulta.setVisible(true);
    }//GEN-LAST:event_jMnuConsultaActionPerformed

    private void jMnuCambiardeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuCambiardeUsuarioActionPerformed
        getFrame().setVisible(false);
        entrarUsuarioyContraseña();
        getFrame().setVisible(true);
    }//GEN-LAST:event_jMnuCambiardeUsuarioActionPerformed

   private void entrarUsuarioyContraseña(){
       boolean continuarEjecutando =true;
       if(continuarEjecutando){
         int i = 1;
         while (i <=3) {
            seguir=false;
            salir=false;
            if (3-i>1){
               vecesMas= 3-i + " veces más.";
            }
            else{
              vecesMas = 3-i + " vez más.";
            }
            Login mLog = new Login(new javax.swing.JDialog(),true);
            mLog.setLocationRelativeTo(null);
            mLog.setVisible(true);
            if (salir){
               System.exit(0);
            }
            if (!seguir){
               if (i>=3){
                  javax.swing.JOptionPane.showMessageDialog(null,  "Contraseña INCORRECTA." + "\n\nHa agotado usted los 3 intentos para introducir la contraseña correctamente." + "\n\n\n\nEL PROGRAMA SE CERRARÁ A CONTINUACIÓN.","Control de Acceso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                  System.exit(0);
               }
               else{
                  javax.swing.JOptionPane.showMessageDialog(null,  "Contraseña INCORRECTA." + "\n\nAsegurese que los carácteres están correctamente escritos, tanto mayúsculas como minúsculas." + "\n\n\n\nPuede volver a intentarlo aún " + vecesMas+ "\n\n\n\nSI NO RECUERDA SU CONTRASEÑA, RECUERDE QUE PUEDE ENTRAR CON SU USUARIO Y COMO CONTRASEÑA PUEDE PONER LA CLAVE DEL DÍA, QUE SE LA DEBE SUMINISTRAR OTRO USUARIO QUE ESTÉ DENTRO DEL SIGO.","Control de Acceso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
               }
            }
            else{
                if (LG_Activo != 1 ){
                   javax.swing.JOptionPane.showMessageDialog(null,  "Lo siento Usuario " + this.wUsuario.toUpperCase() + " su ACCESO está DESHABILITADO." + "\n\n\nConsulte al Departamento de Consultoría.","Control de Acceso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                   if (i>=3){
                      System.exit(0);
                   }
                }
               else{
                   i=4; //Provoco la salida del bucle
               }
            }
            i++;
         } // Fin del While
       } //Fin de If (ContinanuarEjucuatando)

       //EN CONSTRUCCUIO
} // Fin de la función

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLbl_Logo1;
    private javax.swing.JLabel jLbl_Titulo;
    private javax.swing.JMenuItem jMnuCambiardeUsuario;
    private javax.swing.JMenuItem jMnuConsulta;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
    
}
